from __future__ import annotations

import random

LETTERS = [chr(c) for c in range(ord("A"), ord("Z") + 1)]

# 100 unique tech names (no duplicates)
TECH_LIST = [
    "React",
    "Next.js",
    "TypeScript",
    "Node.js",
    "FastAPI",
    "MongoDB",
    "PostgreSQL",
    "Redis",
    "Docker",
    "Kubernetes",
    "AWS",
    "GCP",
    "Azure",
    "Terraform",
    "GitHub Actions",
    "CI/CD",
    "GraphQL",
    "REST",
    "WebSockets",
    "tRPC",
    "Prisma",
    "Drizzle ORM",
    "SQLAlchemy",
    "Celery",
    "RabbitMQ",
    "Kafka",
    "NATS",
    "OpenTelemetry",
    "Prometheus",
    "Grafana",
    "Sentry",
    "Cloudflare",
    "Vercel",
    "Netlify",
    "Auth0",
    "Clerk",
    "Supabase",
    "Firebase",
    "Stripe",
    "PayPal",
    "Twilio",
    "SendGrid",
    "Resend",
    "Algolia",
    "Meilisearch",
    "Elasticsearch",
    "Pinecone",
    "Weaviate",
    "Qdrant",
    "FAISS",
    "LangChain",
    "LangGraph",
    "n8n",
    "OpenAI API",
    "Anthropic API",
    "Hugging Face",
    "RAG",
    "Vector Embeddings",
    "Prompt Engineering",
    "LLM Evaluation",
    "Feature Flags",
    "A/B Testing",
    "Storybook",
    "Tailwind CSS",
    "Radix UI",
    "Shadcn UI",
    "Chakra UI",
    "MUI",
    "Framer Motion",
    "D3.js",
    "Mapbox",
    "Leaflet",
    "React Native",
    "Expo",
    "SwiftUI",
    "Kotlin",
    "Android",
    "iOS",
    "Electron",
    "Tauri",
    "Bun",
    "Deno",
    "Go",
    "Rust",
    "Java",
    "Spring Boot",
    "Django",
    "Flask",
    "Express",
    "NestJS",
    "Svelte",
    "Vue",
    "Angular",
    "Cypress",
    "Playwright",
    "Jest",
    "Vitest",
    "Testing Library",
    "Zod",
    "Pydantic",
    "OAuth",
    "RBAC",
]

# 15 questions total (5 per round)
QUESTIONS = {
    1: [
        {
            "question": "What does SaaS stand for?",
            "options": ["Software as a Service", "System as a Server", "Storage as a Solution", "Software and Support"],
            "answer": "Software as a Service",
        },
        {
            "question": "Which is a common pricing model for SaaS?",
            "options": ["One-time purchase", "Subscription", "Barter", "Lottery"],
            "answer": "Subscription",
        },
        {
            "question": "What is an LLM most commonly used for?",
            "options": ["Generating and understanding text", "Mining coal", "Designing hardware chips", "Compressing images only"],
            "answer": "Generating and understanding text",
        },
        {
            "question": "In a web app, what is a 'backend' responsible for?",
            "options": ["UI animations", "Business logic and data", "Only CSS", "Only icons"],
            "answer": "Business logic and data",
        },
        {
            "question": "What does MVP mean in product building?",
            "options": ["Most Valuable Player", "Minimum Viable Product", "Multi Version Program", "Main Visual Page"],
            "answer": "Minimum Viable Product",
        },
    ],
    2: [
        {
            "question": "What is RBAC?",
            "options": ["Role-Based Access Control", "Random Backend API Calls", "Rapid Build and Compile", "Remote Basic Auth Client"],
            "answer": "Role-Based Access Control",
        },
        {
            "question": "What does multi-tenant mean in SaaS?",
            "options": ["Multiple buildings", "Multiple users share one app with isolated data", "Multiple laptops", "Multiple monitors"],
            "answer": "Multiple users share one app with isolated data",
        },
        {
            "question": "RAG stands for:",
            "options": ["Retrieve and Generate", "Read and Graph", "Route and Guard", "Render as Grid"],
            "answer": "Retrieve and Generate",
        },
        {
            "question": "Which database is document-based?",
            "options": ["MongoDB", "PostgreSQL", "SQLite", "MySQL"],
            "answer": "MongoDB",
        },
        {
            "question": "What is a good Micro SaaS idea trait?",
            "options": ["Solves one narrow problem well", "Tries to replace all apps", "Needs 50 features at launch", "No target users"],
            "answer": "Solves one narrow problem well",
        },
    ],
    3: [
        {
            "question": "Why is showing sources in AI UX useful?",
            "options": ["Builds trust and lets users verify", "Makes UI slower always", "Removes the need for testing", "Stops users from reading"],
            "answer": "Builds trust and lets users verify",
        },
        {
            "question": "Which is a safe AI product pattern?",
            "options": ["Human review before high-stakes actions", "Auto-delete user data", "Hide errors", "No undo"],
            "answer": "Human review before high-stakes actions",
        },
        {
            "question": "What is a common DevOps practice?",
            "options": ["CI/CD pipelines", "Hardcoding secrets", "No monitoring", "Deploying once a year"],
            "answer": "CI/CD pipelines",
        },
        {
            "question": "What does an API do?",
            "options": ["Lets systems communicate", "Designs logos", "Cools servers physically", "Only stores images"],
            "answer": "Lets systems communicate",
        },
        {
            "question": "In voting rules, which is NOT allowed?",
            "options": ["Voting your own tech", "Voting once", "Selecting a tech", "Seeing results after voting"],
            "answer": "Voting your own tech",
        },
    ],
}


def pick_random(items: list[str]) -> str:
    return random.choice(items)

